### ISSUE TITLE
signature parsing fail

### ISSUE THREAD

**Issue by nadako** [snowkit/atom-haxe#19]
``` haxe
class Main {
    static function f(a:Int, ?b:String->Void, ?c:Float) {}

    static function main() {
        Main.
    }
}
```

![](http://take.ms/hcD8s)

**Comment by nadako** [comment]
One more:

``` haxe
class Main {
    static function f(opts:{f:Int}) {}

    static function main() {
        Main.f();
    }
}
```

![](http://take.ms/DsdZN)

**Comment by jeremyfa** [comment]
The first one is the same problem as #14, and I don't reproduce it on my side with the exact same signature (see picture):

![capture d ecran 2015-03-18 a 01 19 54](https://cloud.githubusercontent.com/assets/164094/6700337/edabf6c8-cd0c-11e4-870a-fecd29fe18c1.png)

I need to find what is the origin of the problem.

For the second one, it is a case that was not handled but I will fix it tomorrow.

**Comment by nadako** [comment]
> The first one is the same problem as #14, and I don't reproduce it on my side with the exact same signature

hmm, maybe it's somehow related to haxe compiler version, although I don't think the completion output changed. could you post your completion query results?

**Comment by jeremyfa** [comment]
```
<list>
<i n="f"><t>a : Int -&gt; ?b : (String -&gt; Void) -&gt; ?c : Float -&gt; Unknown&lt;0&gt;</t><d></d></i>
<i n="main"><t>Void -&gt; Unknown&lt;1&gt;</t><d></d></i>
</list>
```

**Comment by nadako** [comment]
I'm getting optional vars wrapped in `Null<T>` (which is correct, I guess), so the problem is with parsing type parameters.

```
<list>
<i n="f"><t>a : Int -&gt; ?b : Null&lt;String -&gt; Void&gt; -&gt; ?c : Null&lt;Float&gt; -&gt; Unknown&lt;0&gt;</t><d></d></i>
<i n="main"><t>Void -&gt; Unknown&lt;1&gt;</t><d></d></i>
</list>
```

**Comment by jeremyfa** [comment]
Thanks for the output. I am fixing it now :)

**Comment by jeremyfa** [comment]
#14 is fixed, now finishing handling typedefs

**Comment by nadako** [comment]
still not quite right:
![](http://take.ms/8kXWp)
![](http://take.ms/TkRjU)

Stripping `Null<T>` might (or might not) be a good idea for optional arguments (that are marked with `?`, but removing nested `Null<T>` only causes confusion.

**Comment by jeremyfa** [comment]
Right, thanks for the detailed report

**Comment by ruby0x1** [comment]
Don't remove the `Null<T>` from optional, it's important for users (esp. those that rely on completion heavily) to learn the language as it is, rather than have it masked and be different elsewhere.
Consistency is best.  It IS a `Null<T>`, don't hide that :)

**Comment by jeremyfa** [comment]
Perfectly ok with that, except that apparently, the compiler seems to wrap optional arguments in Null< > when there was none at the first place.

**Comment by jeremyfa** [comment]
(That said, I didn't reproduce this on my side)

**Comment by jeremyfa** [comment]
I will strip none of them, so we can see if there is something not right somewhere else at least.

**Comment by ruby0x1** [comment]
fwiw I think we are both on 3.2.0 now, maybe double check the version running is not lingering from prior launches? Seems odd that the output would differ though..

**Comment by jeremyfa** [comment]
Parsing issues should be solved by now. Didn't cleared up this wrapping of Null<T> on optional params though. I am normally using haxe 3.2.0 for completion as well, but will double check it doesn't mess up with previous launches as you said.

**Comment by ruby0x1** [comment]
sounds good, i'll test shortly!
